#!/usr/bin/env python3
"""Build CATALOG.md from authored skills/ and optional vendor/ trees."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
VENDOR = ROOT / "vendor"
OUT = ROOT / "CATALOG.md"

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)


def parse_frontmatter(skill_md: Path) -> dict[str, str]:
    text = skill_md.read_text(encoding="utf-8", errors="replace")
    m = FRONTMATTER_RE.match(text)
    meta: dict[str, str] = {}
    if not m:
        return meta
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        meta[k.strip()] = v.strip().strip('"').strip("'")
    return meta


def find_skills(root: Path) -> list[tuple[str, Path, dict[str, str]]]:
    found: list[tuple[str, Path, dict[str, str]]] = []
    if not root.exists():
        return found
    for skill_md in sorted(root.rglob("SKILL.md")):
        # Skip nested examples deep under vendor noise when > 6 levels from root? Keep all.
        name = skill_md.parent.name
        meta = parse_frontmatter(skill_md)
        if meta.get("name"):
            name = meta["name"]
        found.append((name, skill_md, meta))
    return found


def license_hint(skill_dir: Path) -> str:
    for cand in ("LICENSE", "LICENSE.txt", "LICENSE.md", "NOTICE"):
        if (skill_dir / cand).exists():
            return cand
    return "—"


def main() -> int:
    authored = find_skills(SKILLS)
    lines = [
        "# Skill catalog",
        "",
        "Regenerated by `python3 scripts/build-catalog.py`. Do not hand-edit the auto section.",
        "",
        "## Authored (this repo)",
        "",
        "| name | description | path | license file |",
        "|------|-------------|------|--------------|",
    ]
    for name, path, meta in authored:
        desc = (meta.get("description") or "").replace("|", "\\|")
        if len(desc) > 120:
            desc = desc[:117] + "…"
        rel = path.parent.relative_to(ROOT).as_posix()
        lines.append(f"| `{name}` | {desc} | [`{rel}`]({rel}/) | {license_hint(path.parent)} |")

    lines += [
        "",
        "## Upstream / mirrors",
        "",
        "Sources: [registry/sources.yaml](registry/sources.yaml). Populated under `vendor/` by "
        "`scripts/sync-vendor.sh` (gitignored). Attribution: [docs/ATTRIBUTION.md](docs/ATTRIBUTION.md).",
        "",
    ]

    if VENDOR.exists() and any(VENDOR.iterdir()):
        lines += [
            "| name | source tree | description |",
            "|------|-------------|-------------|",
        ]
        for name, path, meta in find_skills(VENDOR):
            try:
                rel = path.parent.relative_to(VENDOR).as_posix()
            except ValueError:
                rel = str(path.parent)
            desc = (meta.get("description") or "").replace("|", "\\|")
            if len(desc) > 100:
                desc = desc[:97] + "…"
            lines.append(f"| `{name}` | `vendor/{rel}` | {desc} |")
    else:
        lines.append("_Run `bash scripts/sync-vendor.sh` then re-run this script to index vendor skills._")

    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(authored)} authored skills)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
