#!/usr/bin/env python3
"""Build CATALOG.md from authored skills/ and optional vendor/ trees."""

from __future__ import annotations

import re
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
VENDOR = ROOT / "vendor"
OUT = ROOT / "CATALOG.md"
ALIASES = ROOT / "registry" / "skill-aliases.json"

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)


def parse_frontmatter(skill_md: Path) -> dict[str, str]:
    text = skill_md.read_text(encoding="utf-8", errors="replace")
    m = FRONTMATTER_RE.match(text)
    meta: dict[str, str] = {}
    if not m:
        return meta
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        meta[k.strip()] = v.strip().strip('"').strip("'")
    return meta


def find_skills(root: Path) -> list[tuple[str, Path, dict[str, str]]]:
    found: list[tuple[str, Path, dict[str, str]]] = []
    if not root.exists():
        return found
    for skill_md in sorted(root.rglob("SKILL.md")):
        # Skip nested examples deep under vendor noise when > 6 levels from root? Keep all.
        name = skill_md.parent.name
        meta = parse_frontmatter(skill_md)
        if meta.get("name"):
            name = meta["name"]
        found.append((name, skill_md, meta))
    return found


def license_hint(skill_dir: Path) -> str:
    for cand in ("LICENSE", "LICENSE.txt", "LICENSE.md", "NOTICE"):
        if (skill_dir / cand).exists():
            return cand
    return "—"


def load_aliases() -> dict[str, str]:
    try:
        raw = json.loads(ALIASES.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    aliases = raw.get("aliases", {})
    return {str(alias): str(target) for alias, target in aliases.items()} if isinstance(aliases, dict) else {}


def brief(description: str) -> str:
    text = re.split(r"(?<=[.!?。！？])\s+", description.strip(), maxsplit=1)[0]
    return text if len(text) <= 96 else text[:93] + "…"


def version_hint(meta: dict[str, str], skill_dir: Path) -> str:
    declared = meta.get("version")
    if declared:
        return f"v{declared.lstrip('v')}"
    try:
        rel = skill_dir.relative_to(ROOT).as_posix()
        out = subprocess.run(
            ["git", "log", "-1", "--format=%h", "--", rel],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        ).stdout.strip()
        if out:
            return f"git:{out}"
    except OSError:
        pass
    return "unversioned"


def main() -> int:
    authored = find_skills(SKILLS)
    aliases = load_aliases()
    lines = [
        "# Skill catalog",
        "",
        "Regenerated by `python3 scripts/build-catalog.py`. Do not hand-edit the auto section.",
        "",
        "## Authored (this repo)",
        "",
        "| id | shortcuts | brief | version | path | license file |",
        "|----|-----------|-------|---------|------|--------------|",
    ]
    for name, path, meta in authored:
        desc = (meta.get("description") or "").replace("|", "\\|")
        rel = path.parent.relative_to(ROOT).as_posix()
        shortcuts = [alias for alias, target in aliases.items() if target in {name, path.parent.name}]
        commands = " ".join(f"`{alias}`" for alias in shortcuts) or "—"
        lines.append(
            f"| `{name}` | {commands} | {brief(desc)} | {version_hint(meta, path.parent)} | "
            f"[`{rel}`]({rel}/) | {license_hint(path.parent)} |"
        )

    lines += [
        "",
        "## Upstream / mirrors",
        "",
        "Sources: [registry/sources.yaml](registry/sources.yaml). Populated under `vendor/` by "
        "`scripts/sync-vendor.sh` (gitignored). Attribution: [docs/ATTRIBUTION.md](docs/ATTRIBUTION.md).",
        "",
    ]

    if VENDOR.exists() and any(VENDOR.iterdir()):
        lines += [
            "| name | source tree | description |",
            "|------|-------------|-------------|",
        ]
        for name, path, meta in find_skills(VENDOR):
            try:
                rel = path.parent.relative_to(VENDOR).as_posix()
            except ValueError:
                rel = str(path.parent)
            desc = (meta.get("description") or "").replace("|", "\\|")
            if len(desc) > 100:
                desc = desc[:97] + "…"
            lines.append(f"| `{name}` | `vendor/{rel}` | {desc} |")
    else:
        lines.append("_Run `bash scripts/sync-vendor.sh` then re-run this script to index vendor skills._")

    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(authored)} authored skills)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
